PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX BFO: <http://purl.obolibrary.org/obo/BFO_>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX MONDO: <http://purl.obolibrary.org/obo/MONDO_>

SELECT ?id ?cohd
WHERE {
    ?id (rdfs:subClassOf)* MONDO:0000001 .
    ?cohd owl:equivalentClass ?id .
    FILTER regex(str(?cohd), "^http://purl.obolibrary.org/obo/COHD_") 
}
