PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX BFO: <http://purl.obolibrary.org/obo/BFO_>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT ?id ?snomed
WHERE {
    ?id oboInOwl:hasDbXref ?snomed .
    FILTER regex(?snomed, "^SNOMEDCT_US") 
}
